# C/C++ with GCC

# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      apt-get install build-essential autoconf libtool pkg-config
      apt-get install cmake
      apt-get install clang-5.0 libc++-dev
      git submodule update --init
      cd cmake/buildcmake ../..
      make
